let suggestions = [

    "Location of AfroBeta",
    "AfroBeta Consult Offices",
    "Founder of AfroBeta",
    "Team members of AfroBeta",
    "Email of AfroBeta",
    "How to get in touch with AfroBeta",
    "Blog Section",
    "Alvin Rita",
    "Emmanuel Misiati",
    " Susan Makori Kwamboka",
    "Features of AfroBeta Consult",
    "Contacts of AfroBeta Consult",
    "Our Services",
    "Our Team",
    "About AfroBeta Consult",
    "Quick Enquiry to AfroBeta Consult",
    "Our solutions at AfroBeta Consult",
    "Testimonials About AfroBeta Consult",
    "Peter Simboni",
    "Terry",
    "Francis Wainaina",
    "Jonathan Githire",
    "5 Recruitment tips for your community program",
    "Participants are using their phones too much!",
    "5 Hacks for sparking participation during training and facilitation",
    "ENERGY! 5 factors to consider when managing energy during training or facilitation ",
    "Six key factors to consider during a facilitation experience",
    "Our Contacts",
    "Our Location",
    "Our Mobile Number",
    "Our Email",
    "Our Vision",
    "Our Mission",
    "Why Afrobeta Consult",
    " Our Values",
    " Our Latest Blog Articles",
    " Our Blog Posts",
    " Creative Director Alvin Rita",
    "  Founder Emmanuel Misiati",
    " C.O.O Susan Kwamboka Makori",
    " Facilitation at AfroBeta Consult",
    " Consultation at AfroBeta Consult",
    " Training at AfroBeta Consult",
    " Training ",
    " Consultaion ",
    " Faciltation ",
    " AfroBeta Clients",
    " Taifa Teule Leadership Experience",
    " TEACHER! TEACHER! Three simple reasons why you are a good one",
    " 4 Simple ways of preparing to facilitate a group session effectively.",
    " 5 Simple steps to building a great team within a short period of time ",
    " ENGAGE. What is something you have been thinking of doing?",
    " 5 Tips for Highly Effective Recruitment Calls for a Volunteer Program",
    " Once is Never Enough; A Facilitator’s Experience",
    " Recent Posts",
    "Misiati",
    "Nyaga",
    "Makori",


];
